### ISSUE TITLE
middleware is not working properly for title

### ISSUE THREAD

**Issue by Rahemanali-24** [Rahemanali-24/ShopCart-Ecommerce-Backend#3]
```

const {createProductValidator} = require('../../middlewares/product_middlewares');

productRouter.post('/',[createProductValidator],createProduct);

```
**product_middlewares.js**
```

function createProductValidator(req,res,next){
    if(!req.body.title){
        return res.json({
            success:false,
            message:"Title not present in the incoming request",
            data:{},
            error:{
                message:"Request body received without title",

            }
        })
    }

    //if everything looks good we call the next middleware
    next();
}

module.exports = {
    createProductValidator,
}



```

**if i do request with title or without title it give always same error 
"Title not present in the incoming request"**

**with title same error**
![Screenshot from 2024-05-17 10-52-34](https://github.com/Rahemanali-24/ShopCart-Ecommerce-Backend/assets/159017790/7282eedd-68c3-4d14-9715-83c311c1bb7c)
**without title same error**
![Screenshot from 2024-05-17 10-52-41](https://github.com/Rahemanali-24/ShopCart-Ecommerce-Backend/assets/159017790/7cbcb8d0-aa7c-4c8c-9954-a04f4f89375c)

**Comment by renu-123-pixel** [comment]
hey ! can you assign this issue to me?

**Comment by Rahemanali-24** [comment]
@renu-123-pixel this problem i think solve but there is another issue in my latest code  if you can contribute
